"""
ucf_buildings.py — UCF Main Campus Building Directory

This file gives Knightro knowledge of all UCF Main Campus buildings!
Directions are calculated FROM the Engineering Atrium (where Knightro lives).

This gets fed to the Groq AI as context so it can give accurate directions.
"""

# Knightro's location — Engineering Atrium
KNIGHTRO_LAT = 28.6014
KNIGHTRO_LON = -81.1984

# All UCF Main Campus buildings with directions FROM the Engineering Atrium
# Format: "BUILDING NAME": "direction description"
UCF_BUILDINGS = {
    "ENGINEERING I": "very close by, just steps away, address: 12760 PEGASUS DR.",
    "BUSINESS ADMINISTRATION I": "very close by, just steps away, address: 12744 PEGASUS DR.",
    "ENGINEERING II": "very close by, just steps away, address: 12800 PEGASUS DR.",
    "BUSINESS ADMINISTRATION II": "very close by, just steps away, address: 4336 SCORPIUS ST.",
    "BUSINESS ADMIN WALKWAYS": "about a 2-3 minute walk to the southwest, address: 4000 CENTRAL FLORIDA BLVD.",
    "CREOL BUILDING": "about a 2-3 minute walk to the east, address: 4304 SCORPIUS ST.",
    "L3HARRIS ENGINEERING CENTER": "about a 2-3 minute walk to the southeast, address: 4328 SCORPIUS ST.",
    "RESEARCH I": "about a 2-3 minute walk to the northeast, address: 4353 SCORPIUS ST.",
    "BIOLOGICAL SCIENCES BUILDING": "about a 2-3 minute walk to the south, address: 4110 LIBRA DR.",
    "THEATRE": "about a 2-3 minute walk to the southwest, address: 12722 PEGASUS DR.",
    "COLLEGE OF SCIENCES BUILDING": "about a 2-3 minute walk to the west, address: 12716 PEGASUS DR.",
    "HEALTH SCIENCES II WALKWAYS": "about a 2-3 minute walk to the north, address: 4364 SCORPIUS ST.",
    "ARBORETUM PORTABLE": "about a 2-3 minute walk to the southeast, address: 4312 SCORPIUS ST.",
    "HEALTH SCIENCES I": "about a 2-3 minute walk to the north, address: 12805 PEGASUS DR.",
    "TECHNOLOGY COMMONS 2 WALKWAYS": "about a 2-3 minute walk to the west, address: 12710 PEGASUS DR.",
    "PHYSICAL SCIENCES BUILDING": "about a 2-3 minute walk to the south, address: 4111 LIBRA DR.",
    "BIOLOGY ELECTRICAL ROOM": "about a 2-3 minute walk to the south, address: 4000 CENTRAL FLORIDA BLVD.",
    "STUDENT UNION": "about a 2-3 minute walk to the west, address: 12715 PEGASUS DR.",
    "HEALTH SCIENCES II": "about a 2-3 minute walk to the north, address: 4364 SCORPIUS ST.",
    "CHEMISTRY BUILDING": "about a 2-3 minute walk to the southwest, address: 4104 LIBRA DR.",
    "TECHNOLOGY COMMONS II": "about a 2-3 minute walk to the west, address: 12710 PEGASUS DR.",
    "TECHNOLOGY COMMONS I": "about a 2-3 minute walk to the southwest, address: 12704 PEGASUS DR.",
    "COUNSELING & PSYCHOLOGICAL SERVICES": "about a 2-3 minute walk to the south, address: 4090 LIBRA DR.",
    "LIBRARY AUTOMATED RETRIEVAL CENTER": "about a 2-3 minute walk to the west, address: 12701 PEGASUS DR.",
    "TECHNOLOGY COMMONS 1 WALKWAYS": "about a 2-3 minute walk to the southwest, address: 12704 PEGASUS DR.",
    "BUS STOP SHELTER 114": "about a 2-3 minute walk to the south, address: 4000 CENTRAL FLORIDA BLVD.",
    "BUS STOP SHELTER 115": "about a 2-3 minute walk to the south, address: 4000 CENTRAL FLORIDA BLVD.",
    "LIBRARY ARC WALKWAY": "about a 2-3 minute walk to the west, address: 12701 PEGASUS DR.",
    "ARBORETUM GREENHOUSE": "about a 2-3 minute walk to the southeast, address: 4160 LIBRA DR.",
    "PARKING GARAGE  C": "about a 2-3 minute walk to the east, address: 12998 GEMINI BLVD. E.",
    "HEALTH CENTER": "about a 2-3 minute walk to the southwest, address: 4098 LIBRA DR.",
    "JOHN T. WASHINGTON CENTER - TENT": "about a 2-3 minute walk to the west, address: 12795 AQUARIUS AGORA DR.",
    "VETERANS COMMEMORATIVE": "about a 5 minute walk to the northwest, address: ",
    "MATHEMATICAL SCIENCES BUILDING": "about a 5 minute walk to the southwest, address: 4393 ANDROMEDA LOOP N.",
    "BUS STOP SHELTER 113": "about a 5 minute walk to the northwest, address: 4000 CENTRAL FLORIDA BLVD.",
    "HOUSING WATER HEATER BUILDING": "about a 5 minute walk to the south, address: 4000 CENTRAL FLORIDA BLVD.",
    "SUMTER HALL": "about a 5 minute walk to the south, address: 4016 LIBRA DR.",
    "BREVARD HALL": "about a 5 minute walk to the south, address: 4048 LIBRA DR.",
    "JOHN T. WASHINGTON CENTER": "about a 5 minute walk to the west, address: 12795 AQUARIUS AGORA DR.",
    "LIBRA COMMUNITY CENTER": "about a 5 minute walk to the south, address: 4040 LIBRA DR.",
    "SOUTH CELL TOWER": "about a 5 minute walk to the east, address: 12930 GEMINI BLVD. E.",
    "UTILITY BUILDING I": "about a 5 minute walk to the south, address: 4017 LIBRA DR.",
    "JOHN C. HITT LIBRARY": "about a 5 minute walk to the west, address: 12701 PEGASUS DR.",
    "LIBRA COMMUNITY CTR WALKWAYS": "about a 5 minute walk to the south, address: 4040 LIBRA DR.",
    "CLASSROOM BUILDING I": "about a 5 minute walk to the northwest, address: 12601 AQUARIUS AGORA DR.",
    "DISTRICT ENERGY PLANT IV": "about a 5 minute walk to the east, address: 4310 SCORPIUS ST.",
    "REHEARSAL HALL": "about a 5 minute walk to the west, address: 12784 AQUARIUS AGORA DR.",
    "UTILITY BUILDING 3 (CHP)": "about a 5 minute walk to the southeast, address: 12907 GEMINI BLVD. E.",
    "CITRUS HALL": "about a 5 minute walk to the south, address: 4024 LIBRA DR.",
    "MASTER LIFT STATION": "about a 5 minute walk to the southeast, address: 4000 CENTRAL FLORIDA BLVD.",
    "OUTDOOR STUDY PAVILION": "about a 5 minute walk to the southwest, address: 4000 CENTRAL FLORIDA BLVD.",
    "BURNETT HONORS COLLEGE": "about a 5 minute walk to the west, address: 12778 AQUARIUS AGORA DR.",
    "UTILITY BUILDING 5A": "about a 5 minute walk to the southeast, address: 4000 CENTRAL FLORIDA BLVD.",
    "FLAGLER HALL": "about a 5 minute walk to the south, address: 4000 LIBRA DR.",
    "ORANGE HALL": "about a 5 minute walk to the south, address: 4032 LIBRA DR.",
    "JIMMIE FERRELL STUD SERV COMMO - C": "about a 5 minute walk to the south, address: 4151 PYXIS LN.",
    "UTILITY BUILDING 2": "about a 5 minute walk to the northwest, address: 12517 AQUARIUS AGORA DR.",
    "FERRELL COMMONS WALKWAYS": "about a 5 minute walk to the southwest, address: 4115 PYXIS LN.",
    "UTILITY BUILDING 5": "about a 5 minute walk to the south, address: 4000 CENTRAL FLORIDA BLVD.",
    "UTILITY BUILDING 2A": "about a 5 minute walk to the northwest, address: 12517 AQUARIUS AGORA DR.",
    "REFLECTING POND": "about a 5 minute walk to the southwest, address: ",
    "UCF GLOBAL": "about a 5 minute walk to the north, address: 4356 SCORPIUS ST.",
    "CLASSROOM BUILDING II": "about a 5 minute walk to the northwest, address: 12650 GEMINI BLVD. N.",
    "JIMMIE FERRELL STUD SERV COMMO - B": "about a 5 minute walk to the southwest, address: 4157 PYXIS LN.",
    "JIMMIE FERRELL STUD SERV COMMO - G": "about a 5 minute walk to the south, address: 4145 PYXIS LN.",
    "LAKE HALL": "about a 5 minute walk to the southwest, address: 4120 PYXIS LN.",
    "VOLUSIA HALL": "about a 5 minute walk to the southwest, address: 4132 PYXIS LN.",
    "PSYCHOLOGY BUILDING": "about a 5 minute walk to the north, address: 4111 PICTOR LN.",
    "SOUTH TELECOM SWITCH BUILDING": "about a 5 minute walk to the south, address: 12825 GEMINI BLVD. S.",
    "SEMINOLE HALL": "about a 5 minute walk to the south, address: 4008 LIBRA DR.",
    "JIMMIE FERRELL STUD SERV COMMO - F": "about a 5 minute walk to the south, address: 4139 PYXIS LN.",
    "BIKE STORAGE 1": "about a 5 minute walk to the south, address: 4000 CENTRAL FLORIDA BLVD.",
    "PARKING GARAGE  D": "about a 5 minute walk to the north, address: 12898 GEMINI BLVD. N.",
    "HOWARD PHILLIPS HALL": "about a 5 minute walk to the west, address: 4297 ANDROMEDA LOOP N.",
    "JIMMIE FERRELL STUD SERV COMMO - D": "about a 5 minute walk to the south, address: 4121 PYXIS LN.",
    "WATER TOWER": "about a 5 minute walk to the southeast, address: 4000 CENTRAL FLORIDA BLVD.",
    "JIMMIE FERRELL STUD SERV COMMO - H": "about a 5 minute walk to the south, address: 4133 PYXIS LN.",
    "JIMMIE FERRELL STUD SERV COMMO - A": "about a 5 minute walk to the southwest, address: 4115 PYXIS LN.",
    "JIMMIE FERRELL STUD SERV COMMO - E": "about a 5 minute walk to the south, address: 4127 PYXIS LN.",
    "HOUSING ADMINISTRATION BLDG": "about a 5 minute walk to the south, address: 12851 GEMINI BLVD. S.",
    "MILLICAN HALL": "about a 5 minute walk to the southwest, address: 4365 ANDROMEDA LOOP N.",
    "KENNETH G. DIXON CAREER DEVELOPMENT CENTER": "about a 5 minute walk to the north, address: 4123 PICTOR LN.",
    "TREVOR COLBOURN HALL": "about a 5 minute walk to the west, address: 12796 AQUARIUS AGORA DR.",
    "BUS STOP SHELTER 109": "about a 5 minute walk to the south, address: 4000 CENTRAL FLORIDA BLVD.",
    "VISUAL ARTS BUILDING": "about a 5 minute walk to the west, address: 12400 AQUARIUS AGORA DR.",
    "BOILER HOUSE": "about a 5 minute walk to the southwest, address: 4000 CENTRAL FLORIDA BLVD.",
    "BUS STOP SHELTER 110": "about an 8-10 minute walk to the south, address: 4000 CENTRAL FLORIDA BLVD.",
    "KIOSK": "about an 8-10 minute walk to the southwest, address: 4399 ANDROMEDA LOOP",
    "FOOD SERV STORAGE": "about an 8-10 minute walk to the southwest, address: 4000 CENTRAL FLORIDA BLVD.",
    "FACILITY SUPPORT BUILDING": "about an 8-10 minute walk to the southeast, address: 3991 LIBRA DR.",
    "OSCEOLA HALL": "about an 8-10 minute walk to the southwest, address: 4108 PYXIS LN.",
    "PARKING GARAGE H": "about an 8-10 minute walk to the northwest, address: 12638 GEMINI BLVD. N.",
    "PRINT SHOP": "about an 8-10 minute walk to the southeast, address: 3987 LIBRA DR.",
    "BUS STOP SHELTER 111": "about an 8-10 minute walk to the southwest, address: 4000 CENTRAL FLORIDA BLVD.",
    "NICHOLSON SCHOOL OF COMM. & MEDIA": "about an 8-10 minute walk to the northwest, address: 12405 AQUARIUS AGORA DR.",
    "TIMOTHY R. NEWMAN  PAVILION": "about an 8-10 minute walk to the northeast, address: 12950 GEMINI BLVD. E.",
    "CREATIVE SCHOOL FOR CHILDREN 1": "about an 8-10 minute walk to the south, address: 12852 GEMINI BLVD. S.",
    "COLLEGE OF ARTS & HUMANITIES": "about an 8-10 minute walk to the northwest, address: 12421 AQUARIUS AGORA DR.",
    "THERMAL STORAGE TANK": "about an 8-10 minute walk to the northwest, address: 4000 CENTRAL FLORIDA BLVD.",
    "ED COMPLEX & GYM WALKWAYS": "about an 8-10 minute walk to the west, address: 12494 UNIVERSITY BLVD.",
    "COMMUNICATION BLDG WALKWAY": "about an 8-10 minute walk to the northwest, address: 12405 AQUARIUS AGORA DR.",
    "POLK HALL": "about an 8-10 minute walk to the southwest, address: 4096 PYXIS LN.",
    "FAIRWINDS ALUMNI CENTER": "about an 8-10 minute walk to the north, address: 12676 GEMINI BLVD. N.",
    "CREATIVE SCHOOL I PAVILION": "about an 8-10 minute walk to the south, address: 12852 GEMINI BLVD. S.",
    "CREATIVE FOR CHILD 1 WALKWAYS": "about an 8-10 minute walk to the south, address: 12852 GEMINI BLVD. S.",
    "BUS STOP SHELTER 112": "about an 8-10 minute walk to the southwest, address: 4000 CENTRAL FLORIDA BLVD.",
    "TOWERS BUILDING 4": "about an 8-10 minute walk to the northeast, address: 4291 MENSA LN.",
    "PARKING GARAGE  B": "about an 8-10 minute walk to the southwest, address: 4799 HYDRA LN.",
    "LAKE CLAIRE BUILDING 65": "about an 8-10 minute walk to the northwest, address: 12580 GEMINI BLVD. N.",
    "CREATIVE SCHOOL 2": "about an 8-10 minute walk to the south, address: 12840 GEMINI BLVD. S.",
    "TEACHING ACADEMY": "about an 8-10 minute walk to the west, address: 4221 ANDROMEDA LOOP N.",
    "CREATIVE SCHOOL I BARN": "about an 8-10 minute walk to the south, address: 12852 GEMINI BLVD. S.",
    "DUKE ENERGY UNIVERSITY WELCOME CENTER": "about an 8-10 minute walk to the southwest, address: 12585 GEMINI BLVD. S.",
    "LAKE CLAIRE BUILDING 64": "about an 8-10 minute walk to the northwest, address: 12574 GEMINI BLVD. N.",
    "EDUCATIONAL COMPLEX & GYM": "about an 8-10 minute walk to the west, address: 12494 UNIVERSITY BLVD.",
    "LAKE CLAIRE BUILDING 66": "about an 8-10 minute walk to the northwest, address: 12538 GEMINI BLVD. N.",
    "LAKE CLAIRE BUILDING 70": "about an 8-10 minute walk to the northwest, address: 12544 GEMINI BLVD. N.",
    "PARKING GARAGE B - SOLAR PANELS": "about an 8-10 minute walk to the south, address: 4799 HYDRA LN.",
    "PARKING GARAGE I": "about an 8-10 minute walk to the west, address: 4277 GEMINI BLVD. W.",
    "LAKE CLAIRE BUILDING 60": "about an 8-10 minute walk to the northwest, address: 12568 GEMINI BLVD. N.",
    "PERFORMING ARTS CENTER": "about an 8-10 minute walk to the west, address: 12488 CENTAURUS BLVD.",
    "PERFORMING ARTS WALKWAY": "about an 8-10 minute walk to the west, address: 12488 CENTAURUS BLVD.",
    "BUS STOP SHELTER 107": "about an 8-10 minute walk to the northeast, address: 4000 CENTRAL FLORIDA BLVD.",
    "LAKE CLAIRE BUILDING 55": "about an 8-10 minute walk to the west, address: 12612 GEMINI BLVD. N.",
    "LAKE CLAIRE BUILDING 69": "about an 8-10 minute walk to the northwest, address: 12520 GEMINI BLVD. N.",
    "LAKE CLAIRE BUILDING 63": "about an 8-10 minute walk to the northwest, address: 12550 GEMINI BLVD. N.",
    "LYNX TRANSIT STATION": "about an 8-10 minute walk to the west, address: 12370 LEO LN.",
    "CHICK FIL-A RESTAURANT": "about an 8-10 minute walk to the south, address: 12820 GEMINI BLVD. S.",
    "LAKE CLAIRE BUILDING 67": "about an 8-10 minute walk to the northwest, address: 12532 GEMINI BLVD. N.",
    "TOWERS BUILDING 3": "about an 8-10 minute walk to the north, address: 4211 E. PLAZA DR.",
    "LAKE CLAIRE BUILDING 56": "about an 8-10 minute walk to the west, address: 12606 GEMINI BLVD. N.",
    "LAKE CLAIRE BUILDING 61": "about an 8-10 minute walk to the northwest, address: 12562 GEMINI BLVD. N.",
    "LIBRA GARAGE": "about an 8-10 minute walk to the south, address: 3820 LIBRA DR.",
    "KNIGHTS PLAZA": "about an 8-10 minute walk to the north, address: 4200 W. PLAZA DR.",
    "LAKE CLAIRE BUILDING 59": "about an 8-10 minute walk to the northwest, address: 12586 GEMINI BLVD. N.",
    "LAKE CLAIRE BUILDING 68": "about an 8-10 minute walk to the northwest, address: 12526 GEMINI BLVD. N.",
    "LAKE CLAIRE BUILDING 62": "about an 8-10 minute walk to the northwest, address: 12556 GEMINI BLVD. N.",
    "LEISURE POOL SERVICES": "about an 8-10 minute walk to the south, address: 12826 GEMINI BLVD. S.",
    "PARKING GARAGE E": "about an 8-10 minute walk to the northeast, address: 4220 MENSA LN.",
    "MORGRIDGE INT'L READING CENTER": "about an 8-10 minute walk to the southwest, address: 4143 ANDROMEDA LOOP N.",
    "LAKE CLAIRE BUILDING 57": "about an 8-10 minute walk to the west, address: 12600 GEMINI BLVD. N.",
    "LAKE CLAIRE BUILDING 58": "about an 8-10 minute walk to the west, address: 12592 GEMINI BLVD. N.",
    "BUS STOP SHELTER 104": "about an 8-10 minute walk to the northwest, address: 4000 CENTRAL FLORIDA BLVD.",
    "LEISURE POOL SERVICES - TENT": "about an 8-10 minute walk to the south, address: 12826 GEMINI BLVD. S.",
    "RECREATION AND WELLNESS CENTER": "about an 8-10 minute walk to the south, address: 12800 GEMINI BLVD. S.",
    "PARKING GARAGE  A": "about an 8-10 minute walk to the west, address: 12491 UNIVERSITY BLVD.",
    "VISITOR AND PARKING INF.": "about an 8-10 minute walk to the southwest, address: 4000 CENTRAL FLORIDA BLVD.",
    "ADDITION FINANCIAL ARENA": "about an 8-10 minute walk to the north, address: 12777 GEMINI BLVD. N.",
    "WAYNE DENSCH SPORTS CENTER": "about an 8-10 minute walk to the northeast, address: 4180 KEN DIXON WAY",
    "BUS STOP SHELTER 103": "about an 8-10 minute walk to the northwest, address: 4000 CENTRAL FLORIDA BLVD.",
    "BUS STOP SHELTER 105": "about an 8-10 minute walk to the north, address: 4000 CENTRAL FLORIDA BLVD.",
    "TRACK & FIELD SHED": "about an 8-10 minute walk to the northeast, address: 4000 CENTRAL FLORIDA BLVD.",
    "BUS STOP SHELTER 351": "about an 8-10 minute walk to the south, address: 4000 CENTRAL FLORIDA BLVD.",
    "ALPHA EPSILON PHI": "about an 8-10 minute walk to the northwest, address: 4321 GREEK PARK DR.",
    "BUS STOP SHELTER 352": "about an 8-10 minute walk to the south, address: 4000 CENTRAL FLORIDA BLVD.",
    "LAKE CLAIRE UTILITY": "about an 8-10 minute walk to the northwest, address: 12491 GEMINI BLVD. N.",
    "ROTH ATHLETIC CENTER": "about an 8-10 minute walk to the northeast, address: 4192 KEN DIXON WAY",
    "ALPHA XI DELTA": "about an 8-10 minute walk to the west, address: 4101 GREEK PARK DR.",
    "NIKE BUILDING 104": "about an 8-10 minute walk to the south, address: 3756 LIBRA DR.",
    "KAPPA DELTA": "about an 8-10 minute walk to the northwest, address: 4303 GREEK PARK DR.",
    "LAKE CLAIRE RESTROOM BLDG": "about an 8-10 minute walk to the northwest, address: 12491 GEMINI BLVD. N.",
    "NIKE BUILDING 101": "about an 8-10 minute walk to the south, address: 3740 LIBRA DR.",
    "ACADEMIC VILLAGES MAIL CENTER": "about an 8-10 minute walk to the south, address: 4117 URSA MINOR ST.",
    "ALPHA DELTA PI": "about an 8-10 minute walk to the northwest, address: 4207 GREEK PARK DR.",
    "TRACK/SOCCER STADIUM": "about an 8-10 minute walk to the north, address: 4275 E. PLAZA DR.",
    "UCF ARENA WALKWAYS": "about an 8-10 minute walk to the north, address: 12785 GEMINI BLVD. N.",
    "NIKE BUILDING 105": "about an 8-10 minute walk to the south, address: 3748 LIBRA DR.",
    "TOWERS BUILDING 1": "about an 8-10 minute walk to the north, address: 4274 W. PLAZA DR.",
    "LAKE CLAIRE BOATHOUSE": "about an 8-10 minute walk to the northwest, address: 12475 GEMINI BLVD. N.",
    "ECON PAVILION": "about an 8-10 minute walk to the northwest, address: 12483 GEMINI BLVD. N.",
    "FRATERNITY AND SORORITY LIFE": "about an 8-10 minute walk to the west, address: 4100 GREEK PARK DR.",
    "SOFTBALL STADIUM - E": "about an 8-10 minute walk to the east, address: 4055 HOME RUN CT.",
    "NIKE BUILDING 103": "on the far south side of campus, address: 3724 LIBRA DR.",
    "BARBARA YING CENTER": "on the far southwest side of campus, address: 12815 SCHOLARSHIP DR.",
    "KAPPA SIGMA": "on the far northwest side of campus, address: 4322 GREEK PARK DR.",
    "HERCULES BUILDING 109": "on the far south side of campus, address: 4125 URSA MINOR ST.",
    "NICHOLSON FIELD HOUSE": "on the far northeast side of campus, address: 4200 KEN DIXON WAY",
    "ICA FOOTBALL STORAGE": "on the far northeast side of campus, address: 4000 CENTRAL FLORIDA BLVD.",
    "NIKE BUILDING 102": "on the far south side of campus, address: 3732 LIBRA DR.",
    "SOFTBALL STADIUM - A": "on the far east side of campus, address: 4055 HOME RUN CT.",
    "PI BETA PHI": "on the far northwest side of campus, address: 4304 GREEK PARK DR.",
    "CHI OMEGA": "on the far west side of campus, address: 4144 GREEK PARK DR.",
    "SOFTBALL STADIUM - F": "on the far east side of campus, address: 4055 HOME RUN CT.",
    "HERCULES BUILDING 113": "on the far south side of campus, address: 4120 URSA MINOR ST.",
    "SOFTBALL STADIUM - H": "on the far east side of campus, address: 4055 HOME RUN CT.",
    "ZETA TAU ALPHA": "on the far northwest side of campus, address: 4202 GREEK PARK DR.",
    "NIKE BUILDING 107": "on the far south side of campus, address: 3716 LIBRA DR.",
    "DELTA DELTA DELTA": "on the far northwest side of campus, address: 4220 GREEK PARK DR.",
    "KAPPA KAPPA GAMMA": "on the far west side of campus, address: 4176 GREEK PARK DR.",
    "LAKE CLAIRE GAZEBO": "on the far northwest side of campus, address: 12467 GEMINI BLVD. N.",
    "CELESTE HOTEL": "on the far west side of campus, address: 4105 N. ALAFAYA TRL.",
    "SOFTBALL STADIUM - B": "on the far east side of campus, address: 4055 HOME RUN CT.",
    "SUWANNEE PAVILION": "on the far northwest side of campus, address: 12459 GEMINI BLVD. N.",
    "HERCULES BUILDING 108": "on the far south side of campus, address: 4139 URSA MINOR ST.",
    "UTILITY BUILDING 6": "on the far southwest side of campus, address: 4000 CENTRAL FLORIDA BLVD.",
    "HERCULES BUILDING 110": "on the far south side of campus, address: 4133 URSA MINOR ST.",
    "BARBARA YING CENTER - CMMS": "on the far southwest side of campus, address: 12701 SCHOLARSHIP DR.",
    "SOFTBALL STADIUM - D": "on the far east side of campus, address: 4055 HOME RUN CT.",
    "BUS STOP SHELTER 108": "on the far south side of campus, address: 4000 CENTRAL FLORIDA BLVD.",
    "WEKIVA PAVILION": "on the far northwest side of campus, address: 12451 GEMINI BLVD. N.",
    "PARKING GARAGE  F": "on the far north side of campus, address: 4403 KNIGHTS VICTORY WAY",
    "NIKE BUILDING 106": "on the far south side of campus, address: 3708 LIBRA DR.",
    "SOFTBALL STADIUM - C": "on the far east side of campus, address: 4055 HOME RUN CT.",
    "BURNETT HOUSE": "on the far southwest side of campus, address: 1000 CENTRAL FLORIDA BLVD.",
    "PARKING GARAGE G": "on the far north side of campus, address: 4282 W. PLAZA DR.",
    "NEPTUNE BUILDING 157": "on the far south side of campus, address: 3700 LIBRA DR.",
    "SOFTBALL STADIUM - G": "on the far east side of campus, address: 4055 HOME RUN CT.",
    "SCHOLARSHIP HOUSE": "on the far southwest side of campus, address: 12649 TRIANGULUM CT.",
    "HERCULES BUILDING 114": "on the far south side of campus, address: 4128 URSA MINOR ST.",
    "NEPTUNE BUILDING 158": "on the far south side of campus, address: 3692 LIBRA DR.",
    "ALPHA TAU OMEGA": "on the far northwest side of campus, address: 4419 GREEK CT.",
    "KAPPA ALPHA THETA": "on the far northwest side of campus, address: 4400 GREEK CT.",
    "BUS STOP SHELTER 106": "on the far north side of campus, address: 4000 CENTRAL FLORIDA BLVD.",
    "HOUSING ADMINISTRATIVE SERVICES": "on the far south side of campus, address: 3684 LIBRA DR.",
    "HERCULES BUILDING 111": "on the far south side of campus, address: 4155 URSA MINOR ST.",
    "HERCULES BUILDING 112": "on the far south side of campus, address: 4147 URSA MINOR ST.",
    "JOHN EULIANO PARK - B": "on the far north side of campus, address: 4422 KNIGHTS VICTORY WAY",
    "JOHN EULIANO PARK": "on the far north side of campus, address: 4422 KNIGHTS VICTORY WAY",
    "JOHN EULIANO PARK - D": "on the far north side of campus, address: 4422 KNIGHTS VICTORY WAY",
    "RECREATION SUPPORT BUILDING": "on the far south side of campus, address: 12625 SCHOLARSHIP DR.",
    "NEPTUNE BUILDING 156": "on the far south side of campus, address: 3676 LIBRA DR.",
    "JOHN EULIANO PARK - E": "on the far north side of campus, address: 4422 KNIGHTS VICTORY WAY",
    "ACRISURE BOUNCE HOUSE": "on the far northeast side of campus, address: 4465 KNIGHTS VICTORY WAY",
    "JOHN EULIANO PARK - F": "on the far north side of campus, address: 4422 KNIGHTS VICTORY WAY",
    "JOHN EULIANO PARK - G": "on the far north side of campus, address: 4422 KNIGHTS VICTORY WAY",
    "TOWERS BUILDING 2": "on the far north side of campus, address: 4290 W. PLAZA DR.",
    "JOHN EULIANO PARK - C": "on the far north side of campus, address: 4422 KNIGHTS VICTORY WAY",
    "SIGMA CHI": "on the far northwest side of campus, address: 4418 GREEK CT.",
    "WD CENTER FOR STUDENT-ATHLETE LEADERSHIP": "on the far northeast side of campus, address: 4582 KEN DIXON WAY",
    "CHALLENGE COURSE SHED": "on the far southwest side of campus, address: 4000 CENTRAL FLORIDA BLVD.",
    "JOHN EULIANO PARK - A": "on the far north side of campus, address: 4422 KNIGHTS VICTORY WAY",
    "CHALLENGE COURSE PAVILION": "on the far southwest side of campus, address: 4000 CENTRAL FLORIDA BLVD.",
    "RECREATION SRVCS. FIELD MAINT.": "on the far southwest side of campus, address: 12693 SCHOLARSHIP DR.",
    "RECREATION SRVCS FIELD RESTRM": "on the far southwest side of campus, address: 12685 SCHOLARSHIP DR.",
    "EMERGENCY OPERATION CENTER": "on the far south side of campus, address: 3504 PERSEUS LOOP",
    "CHALLENGE COURSE": "on the far southwest side of campus, address: ",
    "LAB & ENVIRONMENTAL SUPPORT": "on the far south side of campus, address: 3512 PERSEUS LOOP",
    "JOHN EULIANO PARK - H": "on the far north side of campus, address: 4422 KNIGHTS VICTORY WAY",
    "PUBLIC SAFETY BUILDING": "on the far south side of campus, address: 3610 LIBRA DR.",
    "RECYCLING CENTER": "on the far south side of campus, address: 4000 CENTRAL FLORIDA BLVD.",
    "FACILITIES & SAFETY STORAGE": "on the far south side of campus, address: 4000 CENTRAL FLORIDA BLVD.",
    "FACILITIES & SAFETY - A": "on the far south side of campus, address: 3528 N. PERSEUS LOOP",
    "COMMUNICATION STORAGE SHED": "on the far south side of campus, address: 4000 CENTRAL FLORIDA BLVD.",
    "RECREATION SERVICES SOCCER FIELD PAVILION": "on the far south side of campus, address: 12669 SCHOLARSHIP DR.",
    "FACILITIES & SAFETY GAS STATION": "on the far south side of campus, address: 4000 CENTRAL FLORIDA BLVD.",
    "NORTH CELL TOWER": "on the far northeast side of campus, address: 4382 W. PLAZA DR.",
    "FACILITIES & SAFETY - B": "on the far south side of campus, address: 3528 N. PERSEUS LOOP",
    "BAND PRACTICE FACILITY": "on the far south side of campus, address: 3518 PERSEUS LOOP",
    "FACILITIES & SAFETY - D": "on the far south side of campus, address: 3546 S. PERSEUS LOOP",
    "BAND PRACTICE TOWER": "on the far south side of campus, address: 3518 PERSEUS LOOP",
    "FACILITIES & SAFETY - E": "on the far south side of campus, address: 3540 E. PERSEUS LOOP",
    "RECREATION SERVICE PAVILION": "on the far southwest side of campus, address: 12677 SCHOLARSHIP DR.",
    "E-85 FILLING STATION": "on the far south side of campus, address: 4000 CENTRAL FLORIDA BLVD.",
    "FACILITIES & SAFETY - C": "on the far south side of campus, address: 3534 W. PERSEUS LOOP",
    "FACILITIES & SAFETY - F": "on the far south side of campus, address: 3544 PERSEUS LOOP",
    "ELECTRIC SUBSTATION 2": "on the far northeast side of campus, address: 4000 CENTRAL FLORIDA BLVD.",
    "FACILITIES & SAFETY BULK STORAGE": "on the far south side of campus, address: 4000 CENTRAL FLORIDA BLVD.",
    "ELECTRIC SUBSTATION 1": "on the far south side of campus, address: 4000 CENTRAL FLORIDA BLVD.",
    "BIO TRANSGENIC GREENHOUSE": "on the far southeast side of campus, address: 12706 ARA DR.",
    "AMPAC RESEARCH FACILITY": "on the far southeast side of campus, address: 12712 ARA DR.",
    "ARA HOOPHOUSE - A": "on the far southeast side of campus, address: 4000 CENTRAL FLORIDA BLVD.",
    "ROBINSON OBSERVATORY": "on the far southeast side of campus, address: 12727 ARA DR.",
    "ARA HOOPHOUSE - B": "on the far southeast side of campus, address: 4000 CENTRAL FLORIDA BLVD.",
    "ARA DRIVE RESEARCH FACILITY": "on the far southeast side of campus, address: 12716 ARA DR.",
    "FIRE STATION NO. 65": "on the far northeast side of campus, address: 4999 KEN DIXON WAY",
    "EMERGENCY SRVCS TRAINING BLDG": "on the far northeast side of campus, address: 14026 MCCOLLOCH RD.",
    "BIOLOGY FIELD RESEARCH CENTER": "on the far southeast side of campus, address: 12724 ARA DR.",
    "WUCF ANTENNA TOWER": "on the far southwest side of campus, address: 3544 PERSEUS LOOP",
    "BIOLOGY RESEARCH HOOP HOUSE": "on the far southeast side of campus, address: 4000 CENTRAL FLORIDA BLVD.",
    "STORM WATER RESEARCH LAB - C": "on the far southeast side of campus, address: 12845 ARA DR.",
    "STORM WATER RESEARCH LAB - B": "on the far southeast side of campus, address: 12845 ARA DR.",
    "UTILITY BUILDING 7": "on the far southwest side of campus, address: 4000 CENTRAL FLORIDA BLVD.",
    "STORM WATER RESEARCH LAB - A": "on the far southeast side of campus, address: 12845 ARA DR.",
    "ENGINEERING RESEARCH PAVILION": "on the far southeast side of campus, address: 12871 ARA DR.",
    "MAE/OM LABORATORY": "on the far southeast side of campus, address: 12765 ARA DR.",
    "ENGINE RESEARCH LAB": "on the far southeast side of campus, address: 12741 ARA DR.",
    "SIEMENS ENERGY CENTER": "on the far southeast side of campus, address: 12781 ARA DR.",
    "CONEX COVE STORAGE 22": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 21": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 20": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 19": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 23": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 18": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 17": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 16": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 24": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 15": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 25": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 14": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 26": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 27": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 13": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 12": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 11": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 10": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 9": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 8": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 7": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 6": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 5": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 4": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 3": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 2": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 1": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CONEX COVE STORAGE 28": "on the far southeast side of campus, address: 12874 ARA DR.",
    "CREATIVE SCHOOL FOR CHILDREN 3": "on the far east side of campus, address: 12894 GEMINI BLVD. S.",
}

def get_buildings_context() -> str:
    """
    Returns a text summary of all UCF buildings.
    This gets added to the AI prompt so it knows where everything is!
    Think of it like giving the AI a campus map to read before answering!
    """
    lines = ["UCF MAIN CAMPUS BUILDING DIRECTORY (directions from Engineering Atrium):"]
    for name, info in UCF_BUILDINGS.items():
        lines.append(f"- {name}: {info}")
    return "\n".join(lines)

if __name__ == "__main__":
    print(f"Total buildings: {len(UCF_BUILDINGS)}")
    print()
    print("Sample directions:")
    sample = list(UCF_BUILDINGS.items())[:5]
    for name, info in sample:
        print(f"  {name}: {info}")
